apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

labels:
- includeSelectors: true
  pairs:
    app: zapomni-landing
    version: v1.0.0

images:
- name: zapomni-landing
  newTag: latest
